Map<String, String> enLang = {
  'appName': 'Tucktek',
  "get_started": "Get Started →",
  "skip": "Skip",
  "next": "Next →",
  "start":"Start",
  "elev_gain":"Elev. Gain",
  "est_time":"Est. Time",
  "choose_activity": "Choose Your Favorite Activity",
  "save": "Save",
  "search":"search..",
  "allow_your_location": "Allow your location",
  "allow_location": "Allow location",
  "lorem": "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut",
  "search_by_location": "Search by location",
  "search_fav": "Search Favorites",
  "search_download": "Search Map ",
  "filter": "Filter",
  "add_new_catch": "Add new catch",
  "add_new_harvest":"Add New Harvest",
"add_new_post":"Add New Post",
  "add_photo_and_video": "Add Photos and Videos",
  "write_something": "Write Something",
  "write_something_hint": "Write Something about your catch...",
  "select_species": "Select Species",
  "select_animal":"Select Animal",
  "select_type":"Select Type",
  "see_all": "See All",
  "weigth": "Weigth",
  "temperature": "Temperature",
  "air_pressure": "Air Pressure",
  "wind": "Wind",
  "winter_sport":"Winter Sport",
  "distance": "Distance",
  "preferences": "Preferences",
  "length": "Length",
  "location_privacy": "Location & Privacy",
  "privacy_type": "Privacy Type",
  "weather": "Weather",
  "weather_data": "Weather Data Is Automatically Retrieved From Location And Time",
  "upload": "Upload",
  "add_new_location": "Add New Location",
  "location_name": "Location name",
  "location": "Location",
  "direction": "Direction",
  "download": "Download",
  "share": "Share",
  "description": "Description",
  "catches": "Catches",
  "forecast": "Forecast",
  "species": "Species",
  "write_a_review": "Write a Review →",
  "score": "Score",
  "review": "Review",
  "submit": "Submit",
  "notification": "Notification",
  "no_notification": "No Notification!",
  "catch": "Catch",
  "comments": "Comments",
  "home": "Home",
  "community": "Community",
  "language": "Language",
  "leaderboard": "Leaderboard",
  "profile": "Profile",
  "catch_detail": "Catch Details",
  "catch_location": "Catch Location",
  "main_info": "Main info",
  "this_month": "This Month",
  "all_month": "All Month",
  "add_at_least": "Add At Least One Emergency Contact",
  "add_now": "Add Now",
  "contact_detail": "Contact Details",
  "suggested": "Suggested",
  "others": "Others",
  "done": "Done",
  "select_gear": "Select Gear Used",
  "brand": "Brand",
  "product_line": "Product Line",
  "shop": "Shop",
  "popular_brand": "Popular Brand",
  "fishing": "Fishing",
  "caming_hiking": "Camping & Hiking",
  "water_sport": "Water Sports",
  "hunting": "Hunting",
  "biking": "Biking",
  "block": "Block",
  "edit":"Edit",
  "delete":"Delete",
  "reviews": "Reviews",
  "see_all_reviews": "See All Reviews",
  "product_detail": "Product Details",
  "category": "Category",
  "model_name": "Model Name ",
  "buy_now": "Buy Now",
  "attractions": "Attractions",
  "feed": "Feed",
  "my_favorite": "My Favorites",
  "activitie": "Activities",
  "downloaded_maps": "Download Maps",
  "you_have_no_activity": "You have no Activity",
  "no_suggestion_find_your": "No Suggestions Find Near You",
  "report": "Report",
  "rate_and_review": "Rate and Review",
  "setting": "Setting",
  "share_app": "Share app",
  "my_feed": "My Feed",
  "my_favorites": "My Favorites",
  "push_notification": "Push notifications",
  "emergency_contact": "Emergency Contact",
  "terms_of_services": "Terms of services",
  "privacy_policy": "Privacy Policy",
  "FAQs": "FAQ s",
  "log_out": "Log out",
  "delete_account": "Delete account",
  "cancel_download": "Delete Downloaded Map",
  "are_you_share_download":"Are you really sure you want to Cancel Download?",
  "delete_successfully":"Delete SuccessFully",
  "account": "Account",
  "legal": "Legal",
  "edit_profile": "Edit Profile",
  "edit" :"Edit",
  "login": "Login",
  "search_here": "Search here...",
  "login_content":"Once you log in to GearPro Guide, you will have access to all the features.",
  "remove_favorite":"Remove Favorite",
  "remove_favorite_content":"Are you sure you want to remove this water from your favorites?",

  "first_name": "Full Name",
  "last_name": "Last Name",
  "email": "Email",
  "phone": "Phone Number",
  "tell_us_about": "Tell us about yourself",
  "take_photo":"Take photo",
  "browse_for_photos":"Browse for photo",
  "cancel":"Cancel",
  "yes_logout":"Yes,Log Out",
  "remove":"Remove",
  "add_new_contact":"Add New Contacts",
  "yes_remove":"Yes Remove",
 "animal_type":"Animal Type",
  "population":"Population",
  "area":"Area",
  'startt':"Start →",
  "time":"Time",
  "finish":"Finish",
  "resume":"Resume",
  "public_catch_spot":"Public Catch Spot",
  "secret_spot":"Secret Spot",
  "catches_logged_with":"Catches Logged With Spot Gets More Views",
  "the_location_and_water":"The Location And Water Is For Your Eyes Only",
  "stop":"Stop",
  "avg_speed":"Avg. Speed.",
  "type":"Type",
  "recently_added":"Recently added",
  "activity_date_and_time":"Activity Date And Time",
  "activity_not_found":"Activity Not Found",
  "intro_desc":"Discover essential gear, save on your favorites, learn important skills, and explore breathtaking destinations. Get ready for unforgettable outdoor adventures with GearPro Guide.",
  "embrance_the_great":"Embrace The Great Outdoors!",
  "congratulation":"Congratulations!",
  "detail":"Detail",
  "see_less":"See Less",
  "see_more":"See more",
  "spot":"Spot",
  "pause":"Pause",
 "add_new_species": "Add New Species",
 "add_new_item": "Add New Post",
  "about_us":"About us",
  "image_loading":"Image Loading....",





  "fav_activity_type":"Favorite Activity types",
  "no_location_found":"No Location Found",
  "please_enter_review":"Please Enter Review",




  //content
  "share_content":"Sharing memorable experiences with friends and followers",
 "logout_content": "Could you please confirm that you want to log out?",
  "remove_contact":"Are you sure you want to Remove this Contact?",
  "delete_account_content":"Are you really sure you want your account deleted forever?",
  "yes_delete":"Yes, Delete",
  "yes_remove":"Yes Remove",
  "data_not_found":"Data Not Found!",
  "please_wait":"Please Wait File Uploading...",

  'location_permission_subtitle' : 'We will get your location city and we will get a list of nearby restaurants and cafes that can provide you with food in magic bags.',
  'Notification' : 'Notification',
  'notification_permission_subtitle' : 'Get push notifications for everything you need to know about exciting new stores, delicious foods, and more!',
"saved_contact":"Saved Contact",
  "profile_content":"Welcome to my profile! Here you'll find a glimpse into your feed, favourites, downloaded maps and activities",
  "leader_board_content":"Leaderboard: Climb to the top and own the leaderboard!",
  "my_feed_content":"Your personalized feed, just for you.",
  "my_favorite_content":"A collection of your most-loved moments.",
  "my_activitie_content":"Stay updated with your latest activity here.",
  "download_map_content":"Downloaded Maps: Explore offline with your downloaded maps.",
  "setting_content":"Customize your experience with just a few clicks.",
"no_feed_title":"There are currently no Feed.",
  "no_feed_content":"Hey there! It looks like there are no community posts yet. Be the first to share something exciting or start a conversation.",
  "no_fav_content":"Looks like there are no favorites saved at the moment",
 "no_fav_title": "There are currently no favorites saved",
  "no_activity_content":"Oops it seems there is no specific activity or request at the moment.",
  "no_download_title":"You have no Downloaded Maps",
 "no_download_content":"Oops! It seems you haven't downloaded any maps yet. Let's get those maps downloaded and explore together!",
  "fishing_content":"Discover the best fishing spots, get real-time weather and water condition updates.. Track your catches, learn about different fish species, and even connect with a community of fellow fishing.",
  "hunting_content":"Access hunting season calendars and discover prime hunting locations. Plan your hunting trips, keep digital hunting journals, and connect with a network of fellow hunters to exchange strategies and stories.",
  "winter_sport_content": "Get information on the top ski resorts, snowboarding parks, and ice skating rinks. Learn about snow conditions, avalanche safety, and essential winter gear. Join discussions on the best winter sports equipment and connect with fellow snow enthusiasts.",
  "camping_content":"Find the best camping sites, hiking trails, and backpacking routes. Access camping and hiking checklists, safety tips, and first-aid guides. Plan group hikes, share your outdoor cooking recipes, and capture stunning nature photos to inspire others",
  "water_sport_content":"Discover the hottest spots for kayaking, paddleboarding, surfing, and more. Get updates on tide and wave conditions, safety guidelines, and gear recommendations. Share your water sports experiences and connect with like-minded enthusiasts.",
  "biking_sport_content":"Explore cycling trails, both on and off-road, and find the best routes for your skill level. Get insights into bike maintenance, gear reviews, and safety tips. Track your rides and set goals.",
  //setting content
  "temp_content":"Keep a check on the temperature.",
  "air_pressure_content":"Stay updated about the current air pressure.",
  "wind_content":"Keep an eye on how the wind direction and speed.",
  "notification_content":"Enable or disable your push notifications here.",
  "emergency_content":"In case of emergency keep this updated.",
  "language_content":"Set your language preferences.",
  "term_service_content":"Read about our terms of services here.",
  "privacy_policy_content":"Read about our privacy policy here.",
  "about_us_content":"You can find about us here.",
  "faq_content":"Frequently Asked Questions and Answers.",
  "log_out_content":"Log out from your Gearpro account",
  "delete_account_content_setting":"Delete you account permanently.",


  //Sucees
  "contact_save_successfully" :"Contact Save Successfully",
  "rate_review_content":"Your feedback is invaluable to us. If you have a moment, please consider rating our app.",

 //Errors
  "enter_name":"Please Enter Name",
  "name":"Name",
  "enter_relationship":"Please Enter RelationShip",
  "enter_email":"Please Enter Email",
  "enter_phone_number":"Please Enter Phone Number",
  "choose_language":"Please Select Language",
  "login_error":"Please Login First",
  "rate_error":"Please Rate First",



// exception
  'something_went_wrong': 'Unfortunately, something went wrong',
  "please_select_privacy_type":"Please Select Privacy Type",
  "please_select_image_video":"Please Select Image or Video",
  "please_write_caption":"Please Write Caption",
  "please_select_species":"Please Select Species",



  'no_internet_connection': 'No Internet Connection',
  'access_denied': 'Access Denied',
  'server_error': 'Server Error',
  'connection_timeout_exception': 'Connection Time Out',
  'explore_no_item_title': 'Unavailable kayaking spots at the moment',
  'explore_no_item_subtitle':
      'In a few minutes you will have kayaking spots at your fingertips. You can shop for folding kayaks on our website foldupkayaks.com'
};
